name: Deploy to Tencent Cloud

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: springboot-app
          path: target/*.jar

      - name: Deploy to Tencent Cloud
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.TENCENT_CLOUD_IP }}
          username: ${{ secrets.TENCENT_CLOUD_USER }}
          key: ${{ secrets.TENCENT_CLOUD_SSH_KEY }}
          source: "target/*.jar"
          target: "/opt/springboot/"
          rm: true

      - name: Execute deploy script
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.TENCENT_CLOUD_IP }}
          username: ${{ secrets.TENCENT_CLOUD_USER }}
          key: ${{ secrets.TENCENT_CLOUD_SSH_KEY }}
          script: |
            cd /opt/springboot
            chmod +x deploy.sh
            ./deploy.sh