name: Deploy to Tencent Cloud

on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Verify Build
        run: |
          ls -la target/
          [ -f target/*.jar ] || exit 1

      - name: Prepare Server Directory
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.TENCENT_CLOUD_IP }}
          username: ${{ secrets.TENCENT_CLOUD_USER }}
          key: ${{ secrets.TENCENT_CLOUD_SSH_KEY }}
          script: |
            mkdir -p /opt/springboot
            chmod 755 /opt/springboot

      - name: Deploy JAR
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.TENCENT_CLOUD_IP }}
          username: ${{ secrets.TENCENT_CLOUD_USER }}
          key: ${{ secrets.TENCENT_CLOUD_SSH_KEY }}
          source: "target/*.jar"
          target: "/opt/springboot/"
          rm: false

      - name: Execute deploy script
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.TENCENT_CLOUD_IP }}
          username: ${{ secrets.TENCENT_CLOUD_USER }}
          key: ${{ secrets.TENCENT_CLOUD_SSH_KEY }}
          script: |
            cd /opt/springboot
            ls -la
            chmod +x deploy.sh
            ./deploy.sh